# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.IntegerField()),
                ('ans', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_class_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('semester', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='teacher_class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherReview.Teacher'),
        ),
    ]
