# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherReview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='ques_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherReview.Questions'),
        ),
    ]
